### ISSUE TITLE
[ChatItem]anwerとsystemにリアクションしたときだけアイコンがずれる

### ISSUE THREAD

**Issue by KoukiNAGATA** [KoukiNAGATA/sushi-chat#458]
サーバー側で添字がずれている可能性

**Comment by KoukiNAGATA** [comment]
@yuta-ike @Eri-0910 
anwerとsystemにリアクションしたときだけアイコンがずれています...

**Comment by KoukiNAGATA** [comment]
これやらかすと
```
(node:27051) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at Function.buildAnswer (/Users/kouki/files/programs/sushi-chat/app/server/src/service/chatItem/ChatItemModelBuilder.ts:78:18)
    at Function.buildReaction (/Users/kouki/files/programs/sushi-chat/app/server/src/service/chatItem/ChatItemModelBuilder.ts:49:16)
    at ChatItemDelivery.postReaction (/Users/kouki/files/programs/sushi-chat/app/server/src/infra/delivery/chatItem/ChatItemDelivery.ts:21:51)
    at ChatItemService.postReaction (/Users/kouki/files/programs/sushi-chat/app/server/src/service/chatItem/ChatItemService.ts:103:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```
が出て、Roomに入れなくなるので早急に対応したい

**Comment by TOMOFUMI-KONDO** [comment]
自分の手元だと、answerでのリアクションでずれてるのは確認できました。systemへのリアクションでは不具合確認できなかったです。

**Comment by TOMOFUMI-KONDO** [comment]
上記、確認したらanswreへのreaction時にはサーバー側でエラーが起こっていてそもそもdeliveryされていなかった。(原因は特定して修正中)
